-- Create passenger_counts table for storing video monitoring data
-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS passenger_counts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    count INTEGER NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add foreign key constraint to trips table (adjust if your trips table has different structure)
ALTER TABLE passenger_counts 
ADD CONSTRAINT fk_passenger_counts_trip_id 
FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE;

-- Create index for faster queries
CREATE INDEX idx_passenger_counts_trip_id ON passenger_counts(trip_id);
CREATE INDEX idx_passenger_counts_recorded_at ON passenger_counts(recorded_at);

-- Add Row Level Security (RLS) policies
ALTER TABLE passenger_counts ENABLE ROW LEVEL SECURITY;

-- Policy to allow read access to authenticated users
CREATE POLICY "Allow read access to authenticated users"
ON passenger_counts FOR SELECT
TO authenticated
USING (true);

-- Policy to allow insert for service role (the video server)
CREATE POLICY "Allow insert for service role"
ON passenger_counts FOR INSERT
TO service_role
WITH CHECK (true);

-- Create a view for trip statistics
CREATE OR REPLACE VIEW trip_statistics AS
SELECT 
    trip_id,
    COUNT(*) as total_recordings,
    AVG(count) as average_passengers,
    MAX(count) as max_passengers,
    MIN(count) as min_passengers,
    MIN(recorded_at) as first_recording,
    MAX(recorded_at) as last_recording
FROM passenger_counts
GROUP BY trip_id;

-- Hardware Integration Tables

-- SMS Logs Table
CREATE TABLE IF NOT EXISTS sms_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(20) NOT NULL,
    message TEXT NOT NULL,
    sms_type VARCHAR(50) NOT NULL, -- 'transaction', 'topup', 'reload', 'trip', 'emergency'
    status VARCHAR(20) DEFAULT 'sent', -- 'sent', 'failed', 'pending'
    trip_id BIGINT,
    transaction_id BIGINT,
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for SMS logs
CREATE INDEX idx_sms_logs_phone_number ON sms_logs(phone_number);
CREATE INDEX idx_sms_logs_sms_type ON sms_logs(sms_type);
CREATE INDEX idx_sms_logs_sent_at ON sms_logs(sent_at);
CREATE INDEX idx_sms_logs_trip_id ON sms_logs(trip_id);

-- RLS for SMS logs
ALTER TABLE sms_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read access to authenticated users on sms_logs"
ON sms_logs FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow insert for service role on sms_logs"
ON sms_logs FOR INSERT
TO service_role
WITH CHECK (true);

-- GPS Locations Table
CREATE TABLE IF NOT EXISTS gps_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude DECIMAL(10, 8) NOT NULL,
    longitude DECIMAL(11, 8) NOT NULL,
    altitude DECIMAL(10, 2),
    speed DECIMAL(10, 2),
    accuracy DECIMAL(10, 2),
    source VARCHAR(20) NOT NULL, -- 'gps', 'ip_geolocation'
    trip_id BIGINT,
    satellite_count INTEGER,
    fix_quality INTEGER,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for GPS locations
CREATE INDEX idx_gps_locations_trip_id ON gps_locations(trip_id);
CREATE INDEX idx_gps_locations_recorded_at ON gps_locations(recorded_at);
CREATE INDEX idx_gps_locations_source ON gps_locations(source);

-- RLS for GPS locations
ALTER TABLE gps_locations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read access to authenticated users on gps_locations"
ON gps_locations FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow insert for service role on gps_locations"
ON gps_locations FOR INSERT
TO service_role
WITH CHECK (true);

-- Emergency Alerts Table
CREATE TABLE IF NOT EXISTS emergency_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_lat DECIMAL(10, 8),
    location_lng DECIMAL(11, 8),
    location_source VARCHAR(20), -- 'gps', 'ip_geolocation', 'unknown'
    location_accuracy DECIMAL(10, 2),
    trip_id BIGINT,
    resolved BOOLEAN DEFAULT FALSE,
    resolved_at TIMESTAMP WITH TIME ZONE,
    resolved_by BIGINT, -- staff user ID
    notes TEXT,
    triggered_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add triggered_at column if it doesn't exist (for existing tables)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'emergency_alerts' AND column_name = 'triggered_at'
    ) THEN
        ALTER TABLE emergency_alerts ADD COLUMN triggered_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
    END IF;
END $$;

-- Create indexes for emergency alerts
CREATE INDEX idx_emergency_alerts_trip_id ON emergency_alerts(trip_id);
CREATE INDEX idx_emergency_alerts_triggered_at ON emergency_alerts(triggered_at);
CREATE INDEX idx_emergency_alerts_resolved ON emergency_alerts(resolved);

-- RLS for emergency alerts
ALTER TABLE emergency_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read access to authenticated users on emergency_alerts"
ON emergency_alerts FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow insert for service role on emergency_alerts"
ON emergency_alerts FOR INSERT
TO service_role
WITH CHECK (true);

CREATE POLICY "Allow update for authenticated users on emergency_alerts"
ON emergency_alerts FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

-- Hardware Status Table
CREATE TABLE IF NOT EXISTS hardware_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component VARCHAR(50) NOT NULL, -- 'sim900a', 'neo6m', 'emergency_button', 'camera'
    status VARCHAR(20) NOT NULL, -- 'online', 'offline', 'error', 'maintenance'
    details JSONB,
    last_check TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for hardware status
CREATE INDEX idx_hardware_status_component ON hardware_status(component);
CREATE INDEX idx_hardware_status_last_check ON hardware_status(last_check);

-- RLS for hardware status
ALTER TABLE hardware_status ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read access to authenticated users on hardware_status"
ON hardware_status FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow insert for service role on hardware_status"
ON hardware_status FOR INSERT
TO service_role
WITH CHECK (true);

CREATE POLICY "Allow update for service role on hardware_status"
ON hardware_status FOR UPDATE
TO service_role
WITH CHECK (true);

-- Create views for hardware statistics
CREATE OR REPLACE VIEW sms_statistics AS
SELECT 
    DATE(sent_at) as date,
    sms_type,
    COUNT(*) as total_sent,
    COUNT(*) FILTER (WHERE status = 'sent') as successful,
    COUNT(*) FILTER (WHERE status = 'failed') as failed
FROM sms_logs
GROUP BY DATE(sent_at), sms_type
ORDER BY date DESC, sms_type;

CREATE OR REPLACE VIEW gps_statistics AS
SELECT 
    DATE(recorded_at) as date,
    source,
    COUNT(*) as total_readings,
    AVG(accuracy) as avg_accuracy,
    AVG(speed) as avg_speed
FROM gps_locations
GROUP BY DATE(recorded_at), source
ORDER BY date DESC, source;

CREATE OR REPLACE VIEW emergency_statistics AS
SELECT 
    DATE(triggered_at) as date,
    COUNT(*) as total_emergencies,
    COUNT(*) FILTER (WHERE resolved = TRUE) as resolved,
    COUNT(*) FILTER (WHERE resolved = FALSE) as unresolved
FROM emergency_alerts
GROUP BY DATE(triggered_at)
ORDER BY date DESC;
